baseurl = "https://nickforr.com/"
languageCode = "en-us"
title = "nickforr"
theme = "blackburn"
author = "Nick Forrester"
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A blog"
  brand = "nickforr"
  #googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "nickforr"
  github = "nickforr"
  stackoverflow = "5812231"
  linkedin = "nick-forrester-2b9b1a66/"
